### ISSUE TITLE
ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by murbard** [airgap-it/beacon-extension#1]
Installed the extension on both Brave and Chromium. The extension appears normally. If I enable developer mode I can generate a mnemonic but "save" seems to do nothing (or maybe it saves, but it doesn't return me to the main screen of the extension).

When I go to the dapp example webpage and click to "Connect Beacon", I see this
(I resized the window manually so that the full error appears)

![image](https://user-images.githubusercontent.com/1591742/73594577-63d1c180-4507-11ea-87ec-39801dfd5cce.png)

**Comment by AndreasGassmann** [comment]
Hi, thanks for the report.

Yes, save does not give any visual feedback right now but should still work.

We have not seen this error before. We tried it on Mac with Chrome and it works. I read that opening unpacked chrome extensions can sometimes lead to issues with paths, which seems to be the case here. Which OS are you using so we can try to reproduce the error here?

**Comment by pascuin** [comment]
Couldn't reproduce the error with Brave on MacOS with the latest Beacon Extension version [v0.2](https://github.com/airgap-it/beacon-extension/releases/tag/v0.2)

**Comment by murbard** [comment]
Installed v0.2 on both Brave and Chromium on Linux, I still get the same error. I note that the version number displayed by the extension is 0.01 (not 0.1 nor 0.2).

**Comment by murbard** [comment]
Running under a fresh install of Chrome in a fresh install of Windows 10 yields the same error

![image](https://user-images.githubusercontent.com/1591742/74964949-3abc9680-540c-11ea-898a-25040b181550.png)

**Comment by pascuin** [comment]
The latest release [v0.3](https://github.com/airgap-it/beacon-extension/releases/tag/v0.3) addresses and fixes this issue.
