### ISSUE TITLE
Mnemonic works weird

### ISSUE THREAD

**Issue by KStasi** [airgap-it/beacon-extension#2]
I try to import my accounts using mnemonic and it derives wrong keys. For instance, this one "skate damp faculty morning bring ridge traffic initial piece annual give say wrestle rare ability" is expected to set `tz1bwsEWCwSEXdRvnJxvegQZKeX5dj6oKEys` and secret `7d4c8c3796fdbf4869edb5703758f0e5831f5081`. Instead, it produces: `tz1SjY9W7puV4rkFgb2sXnk1aHfgAfio7WFb` and `3c351b48aba44e7307fafa8f09422e322be5f33b4702839f72bd3fbe1b70bebc5a2add7f2ab62ef2d7a71510b194ba33b0557e0080453d79c8f94fa8cf7aef21`.

**Comment by AndreasGassmann** [comment]
Hi, thanks for trying out the project.

Could you please tell me what app/wallet you are using as a reference? And do you know what derivation path is used?

I'm getting `tz1SjY9W7puV4rkFgb2sXnk1aHfgAfio7WFb` as an address in AirGap as well, so this matches the Extension (which is to be expected, because the same library is used internally).

**Comment by KStasi** [comment]
I use this resource: https://faucet.tzalpha.net/ and it works fine for [tauitos](https://tezostaquito.io/docs/quick_start.html).

**Comment by pascuin** [comment]
Looks like different derivation paths are used, couldn't find the one that Taquitos uses with a quick search but in the Extension `m/44h/1729h/0h/0h` is currently used.

**Comment by AndreasGassmann** [comment]
I just verified that the extension generates the same address as the ledger does. So it's most likely the derivation path that is different.

**Comment by AndreasGassmann** [comment]
I checked some time ago and we generate the same address as AirGap Vault and Thanos, so I think this is fine. (We do not support Galleon / tezos-client derivation paths or fundraiser accounts).
