### ISSUE TITLE
Get balance: internal server error

### ISSUE THREAD

**Issue by KStasi** [airgap-it/beacon-extension#4]
`Get balance`(https://www.walletbeacon.io/) returns:
```
POST https://tezos-babylonnet-node-1.kubernetes.papers.tech/chains/main/blocks/head/helpers/scripts/run_operation 500 (Internal Server Error)
```

**Comment by AndreasGassmann** [comment]
It seems this is happening if the balance of the address is 0. It does work properly (no error) when the account holds some tokens in that contract. I think here we just have to properly catch the error but it seems that it is working as intended.
