### ISSUE TITLE
operationRequest is not implemented

### ISSUE THREAD

**Issue by KStasi** [airgap-it/beacon-extension#5]
<img width="466" alt="Screenshot 2020-02-10 at 12 36 27" src="https://user-images.githubusercontent.com/31795791/74142636-f8bc7500-4c01-11ea-994f-3c481bbbdfe1.png">

**Comment by AndreasGassmann** [comment]
Yes, only the permission request is done at this time. I'm working on this currently and a new version will be released very soon.

**Comment by pascuin** [comment]
The latest release has broader support for `operationRequest` not all contract calls can be signed yet but check it out https://github.com/airgap-it/beacon-extension/releases/tag/v0.2
