### ISSUE TITLE
Unable to scan QR code with phone

### ISSUE THREAD

**Issue by neocybereth** [airgap-it/beacon-extension#7]
I'm currently unable to scan the QR code with my phone application to connect it to the unpacked browser extension. I'm using an iPhone X.

**Comment by pascuin** [comment]
Thanks for trying out Beacon, can you provide a bit more context. Are you using AirGap Wallet to scan the QR code? Currently the versions in the store do not yet have Beacon support included and there is only version released for [AirGap Wallet Android](https://github.com/airgap-it/airgap-wallet/releases/tag/v3.0.3). We'll push out an AirGap Wallet update at the end of this week or in the beginning of next week that includes the Beacon integration.

**Comment by neocybereth** [comment]
Hey @pascuin. Yup, I'm currently using AirGap Wallet to attempt to scan the QR. And alright, that makes sense as to why it's not working. I'll be on the lookout for the updates, thank you.
