### ISSUE TITLE
Transaction Invalid when using Ledger on carthagenet

### ISSUE THREAD

**Issue by Necroskillz** [airgap-it/beacon-extension#9]
Seems ledger integration is not working. Maybe it's because I'm using carthagenet, but still would be nice if it would work just to try it out there (as I also noticed that airgap wallet cannot be switched to a different network, sou you get an error if you try to use it on carthagenet).

ledger:
![image](https://user-images.githubusercontent.com/346477/86786483-5abfc000-c064-11ea-8f81-69309164b8f9.png)

p2p:
![image](https://user-images.githubusercontent.com/346477/86786726-9f4b5b80-c064-11ea-894a-b149b5999c23.png)

**Comment by AndreasGassmann** [comment]
Hi, thanks for opening the issue.

I'll take a look at this later this week. Carthagenet in the Extension (with Ledger) should work, so it might be a bug.

AirGap is currently not compatible with testnets as you pointed out, but this will change soon. We already have an internal version in testing where carthagenet and local networks are supported. As soon as we're done testing we'll release it. If you're on android we can also send you a test version beforehand if you want to give it a try.

**Comment by AndreasGassmann** [comment]
I finally had time to look into this. It was an issue with the ledger. It has been fixed and we will release a new version with this fix and some other improvements shortly.

Also, we now support testnets in AirGap.

**Comment by Necroskillz** [comment]
Just tested this and it works. Although the extension dialog remains open after you confirm with the ledger. Is this intended?
